name: Update Packagist

on:
  release:
    types: [published]

jobs:
  packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            "https://packagist.org/api/update-package?username=cfuentessalgado&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}" \
            -d "{\"repository\":{\"url\":\"https://github.com/${{ github.repository }}\"}}"
